modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/BrassGoggledCoders/StreetSweeper/issues"
license="MIT"

[[mods]]
    modId="streetsweeper"
    version="${file.jarVersion}"
    displayName="StreetSweeper"
    authors="FreneticScribber"
    description='''
        Caps the number of entities in the world
    '''
